### ISSUE TITLE
Using the -W argument leads to an FFmpeg error

### ISSUE THREAD

**Issue by veikk0** [alexheretic/vimg#6]
Using the -W argument leads to the following error:

```
[AVFilterGraph @ 0x55e98ca698c0] No option name near 'bicubic'
[AVFilterGraph @ 0x55e98ca698c0] Error parsing a filter description around: 
[AVFilterGraph @ 0x55e98ca698c0] Error parsing filterchain 'scale240:-1:flags=bicubic' around: 
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!
------
```
Based on this output, it seems to me like an equals sign is missing from the scale filter.

Command to reproduce:

>vimg vcs -c 3 --avif-crf 45 --avif-preset 6 --avif-fps 24 -W 240 -n 15 -f 120 -o bbbtest.avif big_buck_bunny_1080p_h264.mov

I'm using vimg 0.1.2 and FFmpeg 6.0.

**Comment by alexheretic** [comment]
Thanks for reporting!
